module.exports = [
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Dunk-High-Ambush-Active-Fuchsia.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609406830',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Dunk-High-Ambush-Active-Fuchsia.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609406830',
    },
    _id: '5fffde1a9e0eed9bae0e341c',
    colorway: 'Active Fuchsia/Lethal Pink',
    name: 'Ambush Active Fuchsia',
    retailPrice: 180,
    title: 'Nike Dunk High Ambush Active Fuchsia',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Air-Force-1-Low-Experimental-Racer-Pink.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610190450',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Air-Force-1-Low-Experimental-Racer-Pink.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610190450',
    },
    _id: '5fffde1a9e0eed9bae0e341b',
    colorway: 'Racer Pink/Arctic Punch-Sail-Opti Yellow',
    name: 'Racer Pink',
    retailPrice: 120,
    title: 'Nike Air Force 1 Low Experimental Racer Pink',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-NDSTRKT-Air-Max-95-Neon.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1606849772',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-NDSTRKT-Air-Max-95-Neon.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1606849772',
    },
    _id: '5fffde1a9e0eed9bae0e3419',
    colorway: 'Black/Neon Yellow-Medium Grey',
    name: 'Neon',
    retailPrice: 200,
    title: 'Nike NDSTRKT Air Max 95 Neon',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Air-Foamposite-One-Barely-Green.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610495746',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Air-Foamposite-One-Barely-Green.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610495746',
    },
    _id: '5fffde1a9e0eed9bae0e341a',
    colorway: 'Black/Black-Barely Green-Barely Green',
    name: 'All Star (2021)',
    retailPrice: 230,
    title: 'Nike Air Foamposite One All-Star 2021',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx-assets.imgix.net/media/New-Product-Placeholder-Default.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=0',
      smallImageUrl: 'https://stockx-assets.imgix.net/media/New-Product-Placeholder-Default.jpg?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=0',
    },
    _id: '5fffde1a9e0eed9bae0e3421',
    colorway: 'Multicolor/Multicolor',
    name: 'Chinese New Year Firecracker (2021)',
    retailPrice: 100,
    title: 'Nike Dunk Low Chinese New Year Firecracker (2021)',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Lebron-18-Dunkman.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610048739',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Lebron-18-Dunkman.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610048739',
    },
    _id: '5fffde1a9e0eed9bae0e341d',
    colorway: 'Black/Electric Green-Black',
    name: 'Dunkman',
    retailPrice: 200,
    title: 'Nike Lebron 18 Dunkman',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Dunk-High-PRM-Dark-Russet.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609961520',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Dunk-High-PRM-Dark-Russet.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609961520',
    },
    _id: '5fffde1a9e0eed9bae0e341f',
    colorway: 'Velvet Brown/Dark Russet-Dark Curry-Sail',
    name: 'Dark Russet',
    retailPrice: 120,
    title: 'Nike Dunk High PRM Dark Russet',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Zoom-Freak-2-Alphabet.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609203426',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Zoom-Freak-2-Alphabet.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1609203426',
    },
    _id: '5fffde1a9e0eed9bae0e3422',
    colorway: 'Desert Sand/Sail/Camellia/Gym Red',
    name: 'Alphabet',
    retailPrice: 120,
    title: 'Nike Zoom Freak 2 Alphabet',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Air-Foamposite-Pro-Volt-2021.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610190448',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Air-Foamposite-Pro-Volt-2021.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1610190448',
    },
    _id: '5fffde1a9e0eed9bae0e3420',
    colorway: 'Volt/Volt/Volt',
    name: 'Volt (2021)',
    retailPrice: 230,
    title: 'Nike Air Foamposite Pro Volt (2021)',
    __v: 0,
  },
  {
    media: {
      imageUrl: 'https://stockx.imgix.net/images/Nike-Kyrie-7-Raygun.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1608619683',
      smallImageUrl: 'https://stockx.imgix.net/images/Nike-Kyrie-7-Raygun.png?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1608619683',
    },
    _id: '5fffde1a9e0eed9bae0e341e',
    colorway: 'Black/University Gold-Team Orange',
    name: 'Raygun',
    retailPrice: 130,
    title: 'Nike Kyrie 7 Raygun',
    __v: 0,
  },
];
